services:
  unipark-backend:
    build: .
    container_name: unipark_api
    restart: always
    # Aquí pasamos el .env de forma segura al contenedor en runtime
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # Formato: /ruta/en/tu/servidor:/app/certs:ro
      - ./certs:/app/certs:ro
      - ./logs:/app/logs
        # restart: always